export default {
  bail: 0,
  testEnvironment: "node",
  transform: {},
  testMatch: ["<rootDir>/test/**/*.test.js"],
  globalSetup: "./test/globalSetup.js",
  globalTeardown: "./test/globalTeardown.js",
  slowTestThreshold: 30,
  cacheDirectory: "./tmp",
  setupFiles: ["<rootDir>/test/env.js"],
  setupFilesAfterEnv: [],
  slowTestThreshold: 30,
  automock: false,
  clearMocks: true,
  testTimeout: 120000,
  slowTestThreshold: 90,
};
